### ISSUE TITLE
Extra space below "Navigation Bar"

### ISSUE THREAD

**Issue by saabgeek04** [thennothinghappened/pelorus#6]
![Screenshot_20230830-072934.png](https://github.com/thennothinghappened/pelorus/assets/115202864/a2cf11d5-ffa6-4907-80a4-fdab9168a01c)

Symptoms:
- too much space below the interal(?) navigation bar for the system ui
- happens with gesture or button navigation selected

Attempted troubleshooting so far:
- clear app cache
- restart app
- reinstall app

Summary:
This began occuring after updating to the latest version of pelorus. literally unplayable.

Lmk if you need additional info. 
Android 13
build: TQ3A.230805.001
Pixel 7 Pro

**Comment by thennothinghappened** [comment]
Fixed in 1.6.7.
